### ISSUE TITLE
Bot is waiting for input while building tex

### ISSUE THREAD

**Issue by davidism** [pallets/flask-docs#3]
Ran the builder manually to figure out why nothing was building. Builder is sitting waiting for input, which it will never get. Had to enter Ctrl-D at each of the ? prompts.

```
...
Package hyperref Message: Driver (autodetected): hpdftex.

(/usr/share/texlive/texmf-dist/tex/latex/hyperref/hpdftex.def
(/usr/share/texlive/texmf-dist/tex/latex/oberdiek/rerunfilecheck.sty))
(/usr/share/texlive/texmf-dist/tex/latex/oberdiek/hypcap.sty) (./jinjastyle.sty
 (/usr/share/texlive/texmf-dist/tex/latex/inconsolata/inconsolata.sty))
Writing index file Jinja2.idx
(./Jinja2.aux) (/usr/share/texlive/texmf-dist/tex/latex/base/ts1cmr.fd)
(/usr/share/texlive/texmf-dist/tex/latex/psnfss/t1ppl.fd)
(/usr/share/texlive/texmf-dist/tex/context/base/supp-pdf.mkii
[Loading MPS to PDF converter (version 2006.09.02).]
) (/usr/share/texlive/texmf-dist/tex/latex/oberdiek/epstopdf-base.sty
(/usr/share/texlive/texmf-dist/tex/latex/oberdiek/grfext.sty)
(/usr/share/texlive/texmf-dist/tex/latex/latexconfig/epstopdf-sys.cfg))
*geometry* driver: auto-detecting
*geometry* detected driver: pdftex
(/usr/share/texlive/texmf-dist/tex/latex/hyperref/nameref.sty
(/usr/share/texlive/texmf-dist/tex/generic/oberdiek/gettitlestring.sty))
(./Jinja2.out) (./Jinja2.out)
! Undefined control sequence.
\maketitle ...tnoterule \relax \ifsphinxpdfoutput 
                                                  \begingroup \def \\{, } \p...
l.55 \maketitle
               
? 
```

**Comment by davidism** [comment]
The bot is currently disabled until this can be figured out. New builds must be triggered manually on the server.

**Comment by mitsuhiko** [comment]
Sounds like there is a syntax error in the Jinja2 docs. Will look but I don't have a tex installation on my mac recently since I ran out of disk space so probably need to debug this on the server.

**Comment by davidism** [comment]
This happened for more than Jinja. I had to Ctrl-D for pretty much everything but Click if I remember correctly.

**Comment by mitsuhiko** [comment]
It actually passes for me on the server but it does not generate a PDF. I assume something broke in the theme that is used in those projects. I will try to see if i can debug this locally.

**Comment by danielopitz** [comment]
Some info:
```
! Undefined control sequence.
\maketitle ...tnoterule \relax \ifsphinxpdfoutput
```
`\ifsphinxpdfoutput` is missing and used in `flaskstyle.sty` on line 8. It is referenced in issue https://github.com/sphinx-doc/sphinx/issues/3914 but seems to be fixed. Not sure why it is not working, I tested it with Sphinx > 1.7

```
! Extra \fi.
\maketitle ...) /Title (\@title ) } \endgroup \fi
```
It's the closing `\fi` of `\ifsphinxpdfoutput` and currently has no `\if*` without working `\ifsphinxpdfoutput`. LaTeX mostly ignores these.
```
! Package inputenc Error: Unicode character 🎉 (U+1F389)
(inputenc)                not set up for use with LaTeX.
```
This one has several potential fixes. LaTeX doesn't understand unicode per se (including emoji) and uses control sequences like `\alpha` for Greek letter alpha, especially pdfLaTeX. There are some distributions, like XeLaTeX and LuaLaTeX which do, but the font used for output must include emoji too (e.g. DejaVu Sans) (and one must use XeLaTeX or LuaTeX). Alternative, but not really viable way to fix this, is to use `\DeclareUnicodeCharacter` (e.g. `\DeclareUnicodeCharacter{"00A0}{\nobreakspace}` at the beginning of Flask.tex), but one would need to define one control sequence for every special character. Or just remove the emoji.

I think that's all. If you have any idea where I could try to include a fix, I would be glad for a pointer and could try some things out. For the emoji stuff, there is the option of changing the build process, which is always complicated / not always possible and seems like an overkill in this situation, the emoji character could be deleted or replaced with a nbsp using `\DeclareUnicodeCharacter{1F389}{\nobreakspace}`.
